# Generated by Django 5.0.4 on 2024-04-13 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jwt_auth', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='belongings',
            new_name='affiliation',
        ),
    ]
